import type { Metadata } from "next";

import "./globals.css";
import PageTransition from "@/components/Layout/PageTransition";

export const metadata: Metadata = {
  title: "Bhagya-Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html>
      <body className="min-h-full flex flex-col">
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
