import type { Metadata } from "next";

import "./globals.css";
import PageTransition from "@/components/Layout/PageTransition";
import Navbar from "@/components/Layout/Navbar";
import LenisProvider from "@/Provider/LenisProvider";
import Footer from "@/components/Layout/Footer";

export const metadata: Metadata = {
  title: "Bhagya-Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html>
      <body className="min-h-full flex flex-col">
        <PageTransition>
          <LenisProvider>
            <Navbar />
            {children}
            <Footer />
          </LenisProvider>
        </PageTransition>
      </body>
    </html>
  );
}
